import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";

interface ImageGeneratorProps {
  onBack: () => void;
  onApplyHero: (url: string) => void;
}

export const ImageGenerator: React.FC<ImageGeneratorProps> = ({ onBack, onApplyHero }) => {
  const [prompt, setPrompt] = useState('a girl smile in a office, with white teeths, blonde hair, high resolution dental marketing photography, professional lighting, clean modern aesthetic');
  const [size, setSize] = useState<'1K' | '2K' | '4K'>('1K');
  const [aspectRatio, setAspectRatio] = useState<'1:1' | '16:9' | '4:3'>('16:9');
  const [loading, setLoading] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setLoading(true);
    setError(null);
    setGeneratedImage(null);

    try {
      // Create instance right before call
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const response = await ai.models.generateContent({
        model: 'gemini-3-pro-image-preview',
        contents: {
          parts: [{ text: prompt }]
        },
        config: {
          imageConfig: {
            aspectRatio: aspectRatio,
            imageSize: size
          }
        }
      });

      // Find the image part in the response
      let imageUrl = '';
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }

      if (imageUrl) {
        setGeneratedImage(imageUrl);
      } else {
        throw new Error("No image was generated by the model.");
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to generate image. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen pt-32 pb-20 bg-slate-50">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <button 
          onClick={onBack}
          className="mb-8 flex items-center gap-2 text-purple-600 font-bold hover:text-purple-700 transition-all"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
          Back to Home
        </button>

        <div className="grid lg:grid-cols-3 gap-8 items-start">
          {/* Controls Panel */}
          <div className="lg:col-span-1 space-y-6">
            <div className="bg-white rounded-[32px] p-8 shadow-xl border border-purple-100">
              <h2 className="text-xl font-black text-slate-900 mb-6 flex items-center gap-2">
                <span className="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center text-purple-600">✨</span>
                Marketing Lab
              </h2>

              <div className="space-y-6">
                <div>
                  <label className="block text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Creative Prompt</label>
                  <textarea
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-100 rounded-2xl p-4 text-sm text-slate-700 h-32 focus:ring-2 focus:ring-purple-500 focus:outline-none resize-none transition-all"
                    placeholder="Describe the clinical or lifestyle scene..."
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Image Quality</label>
                    <div className="flex bg-slate-50 p-1 rounded-xl border border-slate-100">
                      {(['1K', '2K', '4K'] as const).map((s) => (
                        <button
                          key={s}
                          onClick={() => setSize(s)}
                          className={`flex-1 py-1.5 text-[10px] font-black rounded-lg transition-all ${
                            size === s ? 'bg-white shadow-sm text-purple-600' : 'text-slate-400 hover:text-slate-600'
                          }`}
                        >
                          {s}
                        </button>
                      ))}
                    </div>
                  </div>
                  <div>
                    <label className="block text-xs font-black text-slate-400 uppercase tracking-widest mb-3">Ratio</label>
                    <div className="flex bg-slate-50 p-1 rounded-xl border border-slate-100">
                      {(['16:9', '4:3', '1:1'] as const).map((r) => (
                        <button
                          key={r}
                          onClick={() => setAspectRatio(r)}
                          className={`flex-1 py-1.5 text-[10px] font-black rounded-lg transition-all ${
                            aspectRatio === r ? 'bg-white shadow-sm text-purple-600' : 'text-slate-400 hover:text-slate-600'
                          }`}
                        >
                          {r}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>

                <button
                  onClick={handleGenerate}
                  disabled={loading}
                  className={`w-full py-4 rounded-2xl font-black text-white transition-all shadow-lg flex items-center justify-center gap-3 ${
                    loading ? 'bg-slate-300 cursor-not-allowed' : 'bg-purple-600 hover:bg-purple-700 shadow-purple-200'
                  }`}
                >
                  {loading ? (
                    <div className="flex items-center gap-2 loader-dots">
                      <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
                      <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
                      <div className="w-1.5 h-1.5 bg-white rounded-full"></div>
                    </div>
                  ) : (
                    <>
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h14a2 2 0 002-2V6a2 2 0 00-2-2H4a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                      <span>Generate Asset</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            <div className="bg-purple-900 rounded-[32px] p-8 text-white space-y-4">
              <h3 className="font-bold text-sm">Design Tips</h3>
              <p className="text-xs text-purple-200 leading-relaxed">
                Use keywords like "cinematic lighting", "macro dental photography", or "Peja office aesthetic" to get localized, high-quality results.
              </p>
            </div>
          </div>

          {/* Result Panel */}
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white rounded-[40px] shadow-2xl overflow-hidden border border-slate-100 min-h-[500px] flex flex-col">
              <div className="p-4 border-b border-slate-50 flex justify-between items-center">
                <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest px-4">AI Output Canvas</span>
                {generatedImage && (
                  <button 
                    onClick={() => onApplyHero(generatedImage)}
                    className="flex items-center gap-2 bg-purple-50 text-purple-700 px-4 py-2 rounded-full font-black text-[10px] uppercase tracking-widest hover:bg-purple-100 transition-all"
                  >
                    Set as Site Hero
                  </button>
                )}
              </div>

              <div className="flex-1 relative flex items-center justify-center p-8 bg-slate-50">
                {loading ? (
                  <div className="text-center space-y-4">
                    <div className="w-16 h-16 border-4 border-purple-200 border-t-purple-600 rounded-full animate-spin mx-auto"></div>
                    <p className="text-slate-500 font-bold animate-pulse">Designing your visual...</p>
                  </div>
                ) : generatedImage ? (
                  <div className="w-full h-full animate-fade-in group relative">
                    <img 
                      src={generatedImage} 
                      alt="Generated" 
                      className="w-full h-auto max-h-[700px] object-contain rounded-2xl shadow-2xl"
                    />
                    <div className="absolute inset-0 ring-1 ring-inset ring-black/10 rounded-2xl pointer-events-none"></div>
                  </div>
                ) : error ? (
                  <div className="text-center space-y-4 text-red-500 max-w-sm px-4">
                    <svg className="w-12 h-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                    <p className="font-bold">{error}</p>
                    <button onClick={handleGenerate} className="text-purple-600 font-black text-xs uppercase underline">Retry Generation</button>
                  </div>
                ) : (
                  <div className="text-center space-y-6 opacity-40 max-w-xs">
                    <div className="w-20 h-20 bg-slate-200 rounded-[30px] flex items-center justify-center mx-auto">
                      <svg className="w-10 h-10 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h14a2 2 0 002-2V6a2 2 0 00-2-2H4a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                    </div>
                    <p className="text-slate-500 font-medium">Ready to visualize. Use the generator on the left to create stunning clinic assets.</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};